export const styles = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: "100vh",
    padding: "20px",
    backgroundColor: "#f5f5f5",
    gap: "30px",
  },
  title: {
    fontSize: "36px",
    fontWeight: "bold" as const,
    margin: "0",
    color: "#333",
  },

  // Game State Display
  gameStateContainer: {
    display: "flex",
    gap: "30px",
    justifyContent: "center",
    padding: "15px 30px",
    backgroundColor: "white",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
    width: "100%",
    maxWidth: "600px",
  },
  gameStatItem: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "8px",
  },
  gameStateLabel: {
    fontSize: "14px",
    fontWeight: "500" as const,
    color: "#666",
  },
  gameStateValue: {
    fontSize: "24px",
    fontWeight: "bold" as const,
    color: "#333",
  },

  // Tableau
  tableauContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "15px",
    width: "100%",
    backgroundColor: "white",
    padding: "20px",
  },
  sectionTitle: {
    margin: "0 0 10px 0",
    fontSize: "18px",
    fontWeight: "bold" as const,
    color: "#333",
  },
  tableau: {
    display: "flex",
    gap: "15px",
    justifyContent: "center",
    flexWrap: "wrap" as const,
  },
  tableauStack: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "8px",
    padding: "15px",
    backgroundColor: "#f9f9f9",
    borderRadius: "6px",
    border: "2px solid #ddd",
    minWidth: "80px",
  },
  tableauLabel: {
    fontSize: "14px",
    fontWeight: "bold" as const,
  },
  tableauCount: {
    fontSize: "32px",
    fontWeight: "bold" as const,
    color: "#333",
  },

  // Discard Pile
  discardContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "15px",
    width: "100%",
    backgroundColor: "white",
    padding: "20px",
  },
  discardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(60px, 1fr))",
    gap: "10px",
    minHeight: "80px",
  },
  discardCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "60px",
    height: "80px",
    borderRadius: "4px",
    border: "2px solid rgba(0,0,0,0.2)",
    cursor: "default",
  },
  discardCardRank: {
    fontSize: "24px",
    fontWeight: "bold" as const,
    color: "white",
    textShadow: "1px 1px 2px rgba(0,0,0,0.3)",
  },
  emptyMessage: {
    gridColumn: "1 / -1",
    textAlign: "center" as const,
    color: "#999",
    padding: "20px",
    margin: 0,
  },

  allHandsContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "15px",
    width: "100%",
    backgroundColor: "white",
    padding: "20px",
  },
  allHandsGrid: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "20px",
  },
  playerHandContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "10px",
    padding: "15px",
    backgroundColor: "#f9f9f9",
    borderRadius: "6px",
    border: "1px solid #eee",
  },
  turnPlayerHandContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "10px",
    padding: "15px",
    backgroundColor: "#f9f9f9",
    borderRadius: "6px",
    border: "1px solid #eee",
    boxShadow: "inset 0 0 15px rgba(0, 123, 255, 0.3), inset 0 0 30px rgba(0, 123, 255, 0.15)",
  },
  playerName: {
    margin: "0",
    fontSize: "16px",
    fontWeight: "bold" as const,
    color: "#333",
  },
  playerHand: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap" as const,
    justifyContent: "center",
  },

  // Cards
  card: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    width: "100px",
    height: "100px",
    borderRadius: "6px",
    border: "2px solid rgba(0,0,0,0.2)",
    position: "relative" as const,
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  otherCard: {
    cursor: "not-allowed",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  ownCard: {
    backgroundColor: "#ccc",
    opacity: 0.6,
    cursor: "pointer",
  },
  cardSelected: {
    transform: "scale(1.1)",
    boxShadow: "0 4px 12px rgba(0,0,0,0.3), 0 0 0 3px #007bff",
  },
  cardRank: {
    fontSize: "30px",
    fontWeight: "bold" as const,
    color: "white",
    textShadow: "1px 1px 2px rgba(0,0,0,0.3)",
  },
  cardColor: {
    fontSize: "12px",
    fontWeight: "bold" as const,
    color: "white",
    textShadow: "1px 1px 2px rgba(0,0,0,0.3)",
  },
  cardKnownInfo: {
    position: "absolute" as const,
    top: "5px",
    right: "5px",
    fontSize: "20px",
    fontWeight: "bold" as const,
    color: "white",
    backgroundColor: "rgba(0,0,0,0.4)",
    padding: "2px 4px",
    borderRadius: "3px",
    textShadow: "1px 1px 1px rgba(0,0,0,0.3)",
  },

  // Actions
  actionsContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "20px",
    width: "100%",
    maxWidth: "800px",
    backgroundColor: "white",
    padding: "20px",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },
  actionGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "10px",
  },
  actionTitle: {
    margin: "0",
    fontSize: "16px",
    fontWeight: "bold" as const,
    color: "#333",
  },
  buttonGroup: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap" as const,
    justifyContent: "center",
  },
  actionButton: {
    padding: "10px 20px",
    fontSize: "14px",
    fontWeight: "bold" as const,
    backgroundColor: "#007bff",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
  buttonDisabled: {
    backgroundColor: "#ccc",
    cursor: "not-allowed",
    opacity: 0.6,
  },

  // Hint Form
  hintForm: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "10px",
  },
  select: {
    padding: "8px",
    fontSize: "14px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontFamily: "inherit",
    backgroundColor: "white",
    cursor: "pointer",
    color: "white",
  },

  // Error
  error: {
    color: "#d32f2f",
    backgroundColor: "#ffebee",
    padding: "12px",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "500" as const,
  },
};
